# Generated by Django 3.1.1 on 2020-10-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='name',
            new_name='uname',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='tname',
        ),
    ]
