# Generated by Django 3.1.1 on 2020-10-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20201011_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='u_name',
            new_name='challenge_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='t_name',
            new_name='team_name',
        ),
    ]
