# Generated by Django 3.1.1 on 2020-10-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20201011_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(choices=[('kss', 'KryptSec'), ('hsh', 'hashdump'), ('mom', 'HackerMoms')], max_length=3),
        ),
    ]
