# Generated by Django 3.1.1 on 2020-10-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_auto_20201011_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
