# Generated by Django 3.1.1 on 2020-10-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_team_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=20),
        ),
    ]
