# Generated by Django 3.1.1 on 2020-10-11 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_auto_20201011_0505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
